### ISSUE TITLE
Support tags with spaces in them

### ISSUE THREAD

**Issue by Ninjani** [out-of-cheese-error/gooseberry#32]
mdbook chapter filenames can't have spaces in them. This should be as simple as 
1. `.replace(" ", "_")` when making each tag_file
2. same for the the mermaid graph

**Comment by oktak** [comment]
I would like to take this.
But could you illustrate more about the behavior if both tags with space and with underscore tags? 
eg: `tag_sea` and `tag sea` ?

if simply using `.replace(" ", "_")`, they will be merged as one.

**Comment by Ninjani** [comment]
Great!

Hmm, a quick fix for now would be to use double underscore `__` and add a note in the README about this (i.e. not to use `__` in tag names). But a better fix would be to assign an ID to each tag and use the ID as the filename instead of the tag itself. This should be easy enough to implement in `markdown.rs` only but to make issue #10 possible the IDs would need to also be stored in the database.

I think the quick fix is acceptable for closing this issue, and I can overhaul the database when working on issue #10. Thoughts?

**Comment by oktak** [comment]
I do the quick fix for this issue.

 #10  looks like quite a big change 😬
