### ISSUE TITLE
.env USERNAME may misuse the OS ENV value

### ISSUE THREAD

**Issue by oktak** [out-of-cheese-error/gooseberry#35]
Hi. I read through CONTRIBUTING.md and followed the steps to run the test. I find the test does not pass. It said `sync` and `tags` tests are failed.

I print `hypothesis_username` in [cli.rs](https://github.com/out-of-cheese-error/gooseberry/blob/main/tests/cli.rs) for debug, and found it is not the same as what I set in the .env file. Instead it is my username on the OS.

**It seems it affects the test only**, but not the main program. It may be due to using `dotenv::var(USERNAME")?;` to get the value.

I suggest use a more specific variable name such as `HYPOTHESIS_USERNAME` to replace `USERNAME`.

OS: Ubuntu 18.04.5
Rust: 1.46.0 (04488afe3 2020-08-24)

P.S. I tried to `unset USERNAME`, and it comes back after I reboot the OS.

**Comment by Ninjani** [comment]
Good point, I hadn't considered this. I've changed it to HYPOTHESIS_NAME (and the DEVELOPER_KEY to HYPOTHESIS_KEY for consistency), could you take a look?

**Comment by oktak** [comment]
Yes. The test can be run successfully now. 😃
