### ISSUE TITLE
No such file or directory during config

### ISSUE THREAD

**Issue by HEmile** [out-of-cheese-error/gooseberry#49]
Hi there, MacOS X Catalina here. When I'm using any config command, i'm getting this error:

```
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: 
   0: ConfigError: "Couldn\'t create database directory \"/Users/emile/Library/Application Support/rs.gooseberry/gooseberry_db\", No such file or directory (os error 2)"

Location:
   src/configuration.rs:154
Location: src/configuration.rs:106
Abort trap: 6
```

This was solved by executing `mkdir /Users/emile/Library/Application\ Support/rs.gooseberry/`, but it sounds like it's better to create this dir automatically.

**Comment by Ninjani** [comment]
Thanks for the issue! I've made a fix, and I'll include it in a release later today.
