### ISSUE TITLE
Add page template

### ISSUE THREAD

**Issue by HEmile** [out-of-cheese-error/gooseberry#52]
## Problem

Gooseberry provides templates for individual annotations. However, I'd like to create pages for individual URI's visited. This means the URI would be repeated at every annotation. 

## Solution
Ideally, one would be able to create a template for the page the annotations will be in as well. This is challenging though because it depends on the hierarchy used what keys will be available. 

So for instance, the 'page template' could be, when hierarchy is eg `['URI']`:

```
---
aliases: []
---

{{#each annotation}} {{annotation}} {{/each}}

---
#gooseberry 
- [link](URI) 
```

**Comment by Ninjani** [comment]
Good idea! I guess the page template would have the same keys as the link template ("name", "relative_path", "absolute_path") as well as "annotations". I'll add this later today.
