### ISSUE TITLE
No newline in index list

### ISSUE THREAD

**Issue by HEmile** [out-of-cheese-error/gooseberry#53]
## Bug description

The index is creating a nice overview of elements in the annotation, but they're missing newlines. For instance, my index.md looks like

```
- [https_github_com_out-of-cheese-error_gooseberry_issues_50](https_github_com_out-of-cheese-error_gooseberry_issues_50.md)- [https_github_com_out-of-cheese-error_gooseberry](https_github_com_out-of-cheese-error_gooseberry.md)
```

which doesn't render as a proper list in Markdown.

- OS: MacOS Catalina

**Comment by Ninjani** [comment]
The expected behavior is that you would add the newline in the template itself. In case there are configurations where the newline isn't wanted.

**Comment by HEmile** [comment]
Apologies, I missed this setting. Works now!
