### ISSUE TITLE
Multiple configuration files

### ISSUE THREAD

**Issue by HEmile** [out-of-cheese-error/gooseberry#54]
## Problem

I have two Obsidian vaults, one for work and one for personal activities. Gooseberry however only allows a single configuration file, meaning I can only set it up for one of these vaults.
## Solution

It would be nice if it were possible to have multiple configuration files, where one of the vaults could be populated by different groups and using different templates.

(Sorry for all the issues! I like it a lot, which is why I'm adding some things I'd really like to have :) )

**Comment by Ninjani** [comment]
I'm really glad you like it and appreciating the issues!

This is already somewhat possible by changing the `$GOOSEBERRY_CONFIG` environment variable. The idea would be to make two config files and then change the variable (with `export GOOSEBERRY_CONFIG="path/to/file.toml") before running gooseberry. You could put this in a bash script to make it a single command. This is a workaround but incorporating this into gooseberry would need a bit of work and may not be very user-friendly for users with a single configuration. I'll think a bit more about it though.

**Comment by HEmile** [comment]
Alright, that makes sense! If it's not something for the short term, I'll indeed just make a batch script for this :) Glad to know it's possible in that way!

**Comment by Ninjani** [comment]
This turned out to be easy to implement without breaking existing behavior. In the next release you'll be able to use `gooseberry --config=path/to/file.toml <subcommand>` to change the configuration. If run without the option (as `gooseberry <subcommand>`) then it uses the default location or the GOOSEBERRY_CONFIG environment variable if it's set.
