### ISSUE TITLE
'gooseberry make' crashes

### ISSUE THREAD

**Issue by muralikodali** [out-of-cheese-error/gooseberry#61]
gooseberry make fails with following output :  

```
✔ Clear knowledge base directory? · no
⠁
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: /home/xxxx/Downloads/gooseberry/src/gooseberry/knowledge_base.rs:275
fish: “./gooseberry make” terminated by signal SIGABRT (Abort)
```

**Comment by Ninjani** [comment]
Seems to be because the "file_extension" configuration variable is empty. Can you confirm that this is the case?

**Comment by muralikodali** [comment]
Thanks for your suggestion

i am using old version of gooseberry. with updating gooseberry and changing configuration, 'gooseberry make' is producing markdown and SUMMARY files in a configured directory. but is not producing wiki to open in a browser.

mdbook version is v0.4.6

directory structure produced by  previous version :  

![screenshot_20210211124819](https://user-images.githubusercontent.com/11482766/107610847-95c44a80-6c68-11eb-8218-d3e4aed5088e.png)

directoy structure produced by current version:  
 
![screenshot_20210211124917](https://user-images.githubusercontent.com/11482766/107610879-aeccfb80-6c68-11eb-9dff-af2f11229e4e.png)

**Comment by Ninjani** [comment]
Yes, this is because Gooseberry is now independent of mdbook and can be used with any plain text knowledge base system. To set it up with mdbook you will have to run `mdbook init`, and then set up gooseberry's `kb_dir` to point to the `book` directory that's created. This should recreate the same directory order as before.

**Comment by muralikodali** [comment]
pointing knowledge base directory to `src`  folder and running command `mdbook serve`  in  the folder containing `src` folder opened web page containing gooseberry tags without any error.

Thanks @Ninjani
