### ISSUE TITLE
Is it possible to include the website title

### ISSUE THREAD

**Issue by adxrgh** [out-of-cheese-error/gooseberry#69]
## Problem

I hope the title of the website can be included, Not just the ID, since It contains more information. But i couldn't find any field to represent it. But it is possible in the webpages of hypothesis

**Comment by Ninjani** [comment]
Great idea, I somehow forgot about this. Adding it to the next release!

**Comment by Ninjani** [comment]
Done, in 0.7.0 - you can use `{{ title }}` in the template. Thanks!
