### ISSUE TITLE
Newlines in annotations aren't escaped in preview

### ISSUE THREAD

**Issue by ngirard** [out-of-cheese-error/gooseberry#74]
Using home-made binary from the trunk, on Ubuntu 20.04.
Here's an example output of `gooseberry search`:

![Screenshot_20210413_164714](https://user-images.githubusercontent.com/98098/114573180-718ce600-9c78-11eb-9fdb-6b165cce5a48.png)

Installed the very last version of Bat, to no effect.

**Comment by Ninjani** [comment]
Is bat working on other markdown files with the settings `bat -l markdown --color=always -p`?

**Comment by ngirard** [comment]
> Is bat working on other markdown files with the settings `bat -l markdown --color=always -p`?

My bad, I misread you and thought these options had to be added somewhere in Gooseberry's config.

Sure, Bat displays my markdown files just fine. There's nothing related to Bat or a custom pager in my configuration (as far as I could check).

**Comment by Ninjani** [comment]
Hmm, okay let's try to narrow down what's causing this - do you see the same thing happening when you run `gooseberry view`? (Probably a good idea to filter to a particular pattern/day so your terminal isn't filled with output)

**Comment by ngirard** [comment]
> do you see the same thing happening when you run `gooseberry view`?

I don't.

**Comment by Ninjani** [comment]
Okay, then it seems to be a [skim](https://github.com/lotabout/skim) issue. The relevant function is [here](https://github.com/out-of-cheese-error/gooseberry/blob/446ddad21018ca37cb0f520ba020b24259c1576a/src/gooseberry/search.rs#L58) - could you try removing the "-p" in the command and see what change that has?

**Comment by Ninjani** [comment]
Oh wait, why is that a `{:?}`!

**Comment by Ninjani** [comment]
Okay, I think I tried to get away with not escaping newlines etc by using {:?} but guess that doesn't work on Ubuntu sigh.

**Comment by Ninjani** [comment]
`"echo \"{}\" | bat -l markdown --color=always -p",`

Can you try this?

**Comment by ngirard** [comment]
I was expecting the worst... but it worked ! Well done !

**Comment by Ninjani** [comment]
Haha great! I should probably figure out how to test interactivity across devices but until then I'm really appreciating these issues, will be in the next release.

**Comment by ngirard** [comment]
Well then, I'd appreciate you pushed a new release, to spare me with the `build --release`. But if not, no big deal !

**Comment by Ninjani** [comment]
> Well then, I'd appreciate you pushed a new release

Done!
