### ISSUE TITLE
Mention that `--time` expects values in UTC

### ISSUE THREAD

**Issue by ngirard** [out-of-cheese-error/gooseberry#77]
Unless I'm misunderstood, `--time` expects values in UTC.
Mentioning it in the docs would be nice.
Even nicer would be to take values in local time and doing the queries with the local timezone taken into account.

**Comment by Ninjani** [comment]
Good point, this was an easy fix. Next release will use the local timezone, thanks!

**Comment by ngirard** [comment]
Wow nice, thanks !
