### ISSUE TITLE
Provide page URI to templates

### ISSUE THREAD

**Issue by ngirard** [out-of-cheese-error/gooseberry#84]
The templates are currently provided with
- `{{ uri }}` \- Annotation URI
- `{{ base_uri }}` \- Base website of URI

but, unless I'm misunderstood, they cannot render the URI of the original page that was annotated.

I ended up performing regex search & replace against `{{ base_uri }}`, but it would be nice if Gooseberry could add this key to the templates.

**Comment by Ninjani** [comment]
I believe `{{ uri }}` is what you're looking for, the link to the actual annotation is `{{ incontext }}`

**Comment by ngirard** [comment]
Jeez... you're right... I need more sleep, thanks !
Feel free to close this issue whenever you want !
