### ISSUE TITLE
Take into account the existence of `/` in tags when creating the knowledge base directory structure

### ISSUE THREAD

**Issue by ngirard** [out-of-cheese-error/gooseberry#85]
As discusssed in #79, it makes sense for e.g. Obsidian users that tags contain a slash.

However, along with `hierarchy = ['Tag']`, this leads to the following error:
```sh
gooseberry make
✔ Clear knowledge base directory? · yes
Error: 
   0: No such file or directory (os error 2)

Location:
   /home/ngirard/sandboxes/rust/gooseberry.git/src/gooseberry/knowledge_base.rs:370
```

There are several possible strategies in this scenario. The first one to come to mind would be to translate `parent/child1` and `parent/child2` into the following directory structure:
```
kb_dir/
\__ parent/
    \__ child1.md
    \__ child2.md
```
which I'd be fine with ; but I haven gotten further thought about the alternatives.

**Comment by Ninjani** [comment]
> The first one to come to mind would be to translate `parent/child1` and `parent/child2` into the following directory structure:

This ended up being pretty easy to implement but will likely come back to bite me when I get around to adding Windows support in #55 :p

**Comment by ngirard** [comment]
Thank you very much !

> will likely come back to bite me when I get around to adding Windows support

Hopefully replacing all `/` with [std::path::MAIN_SEPARATOR](https://doc.rust-lang.org/std/path/constant.MAIN_SEPARATOR.html) would be enough...?

**Comment by Ninjani** [comment]
Good point, I've done that now and hopefully that'll be the end of it.

**Comment by ngirard** [comment]
Do you feel ready to merge the branch, so I can take advantage of it ?

**Comment by Ninjani** [comment]
I've merged it now, but would like to add some more documentation to the README before making a new release

**Comment by Ninjani** [comment]
I'm reopening this because I want to add a configuration option to set the nested tag character instead of hard-coding it as "/" - for instance in [org-mode this would be " : "](https://orgmode.org/manual/Tag-Hierarchy.html).

**Comment by ngirard** [comment]
Thanks !
And sorry for not contributing to the docs :-/
