### ISSUE TITLE
Use a list of Hypothesis groups instead of just one

### ISSUE THREAD

**Issue by Ninjani** [out-of-cheese-error/gooseberry#9]
A single Hypothesis group is used to pull annotations. Maybe a user would want multiple for different subjects. These can then be used in the annotation template and in the hierarchy configuration.

**Comment by mpr1255** [comment]
Yes! +1 for this. Kagi'd it specifically and found this. Right now I will be hacking some CLI workarounds to do this -- each group in a different top-level folder, for example. Anyway this would be a most welcome feature. Also -- not just a list but an 'all' option -- that would be ideal.

**Comment by Ninjani** [comment]
Added in PR #101 - should already work with `gooseberry config group` as expected, but needs some testing and README updates

**Comment by mpr1255** [comment]
Incredible. So fast. Thank you!! I managed to clone, checkout, and build that version and ran it and the behaviour is _exactly_ as expected, especially with the hierarchical ordering of group_name/title etc. Just brilliant. This saved me from a nutty workaround I had all planned: hit the API to get a list of groups, filter out 'Public', create a gooseberry config.toml for each... etc. etc. Thanks so much. Massively increases usability.
