### ISSUE TITLE
Better filtering

### ISSUE THREAD

**Issue by Ninjani** [out-of-cheese-error/gooseberry#92]
- [x] Add quote and text filter options
- [x] Add an option to filter page notes.

See some comments in #89 [here](https://github.com/out-of-cheese-error/gooseberry/discussions/89#discussioncomment-614873)

**Comment by Ninjani** [comment]
Also add 
- [ ] a way to filter annotations *not* containing a tag 
- [ ] a way to filter annotations containing *any* of the given tags (instead of all)

**Comment by ngirard** [comment]
> - a way to filter annotations not containing a tag
> - a way to filter annotations containing any of the given tags (instead of all)

These ones might be tricky to implement on the CLI side. I'll try to come up with source code to take inspiration from.
Tonight I'm clueless. [Fselect](https://github.com/jhspetersson/fselect) does that, but it leverages its own parser/lexer and it's perhaps too much.
I'll report back when I find something better.

**Comment by ngirard** [comment]
Oh yeah, and there's obviously [Ripgrep](https://github.com/BurntSushi/ripgrep), but as its author said recently on r/rust, the source code isn't always straightforward.
Still, it might be worth taking a look to the code behind the `--type` and `--type-not` options.

**Comment by ngirard** [comment]
Aha. Got one. [Watchexec](https://github.com/watchexec/watchexec) does this in a very straightforward way:
```
OPTIONS:
    (...)
    -f, --filter <pattern>...     Ignore all modifications except those matching the pattern
    -i, --ignore <pattern>...     Ignore modifications to paths matching the pattern
```

**Comment by Ninjani** [comment]
>     -i, --ignore <pattern>...     Ignore modifications to paths matching the pattern

Yeah, I like this one too! I'm thinking something like `--not` instead of ignore since `-i` is already taken by `--include-updated`. This would easily solve the first point (a way to filter annotations not containing a tag).

For the second point (a way to filter annotations containing any of the given tags (instead of all)) I'm thinking of an `--or` flag that flips this behaviour. Any other ideas?

**Comment by ngirard** [comment]
Using `--and` / `--or` / `--not` would allow for maximum flexibility for constructing complex queries, which I think the problem at hand deserves, and would be great.

If you're willing to take that route, you'll probably also need to add parentheses, like [GNU find](https://man7.org/linux/man-pages/man1/find.1.html) (see the *OPERATORS* section) or [Git-annex](https://git-annex.branchable.com/tips/powerful_file_matching/) do.

I just cannot think of relevant code in Rust at the moment.

**Comment by ngirard** [comment]
Jeez... that was fast !

I'll test this as soon as I can, by tomorrow in any case.

**Comment by ngirard** [comment]
I couldn't resist and compiled the branch.

I guess you're aware of this, but just in case:
searching `--tags x --not --tags y` seems to return the union of the sets of 1) annotations tagged x ; 2) annotations not tagged y.
I'd expect the result to be the set of annotations tagged x and not tagged y.

Cheers

**Comment by Ninjani** [comment]
Ooh I didn't actually think of that, right now the `--not` applies to the entire query, and it'll return annotations not tagged with both x and y. Will dive a bit deeper into clap to see how to parse multiple occurrences of an argument separately and also make use of the argument order.

**Comment by ngirard** [comment]
Hence the parentheses...
Yeah, taking a look to an existing implementation with clap would help.

**Comment by Ninjani** [comment]
Looks like clap doesn't really have support for things like this. The only example I could find is [here](https://github.com/jakwings/ff-find) where they write their own [parsing code](https://github.com/jakwings/ff-find/tree/master/src/filter) for filter arguments. I'm considering if it's worth the effort or if there's a simpler workaround on top of the current PR.

One option is to add an `exclude_tags` option, which would make it easy to select annotations containing a certain (set of) tag(s) `x` and not containing another (set of) tag(s) `y`, using `gooseberry search --tags x --exclude-tags y`. Using this with `--or` would return annotations with ANY of `x` and none of `y`, otherwise it'd be ALL of `x` and none of `y`. With `--not` you'd get ANY of `y` and not ALL of `x` (not sure what the use case for that would be but still nice to have)

For everything else I think the current PR and the `search` box should help with more complex queries - to make this smoother I'll add another keyboard shortcut to `search` (probably Shift-Down) which runs `make` on the filtered annotations (this way `search` would pretty much be the only command needed to run everything), and I'll add a `--search` option to the make command as well.

Do you have any other queries/situations in mind that need extra handling? The only one I can think of that can't be handled by search is to find annotations within a certain time period but not on a certain day within that time period or something like that, which can be solved with two searches instead of one (not ideal of course but not a dealbreaker I'd say)

**Comment by ngirard** [comment]
> The only example I could find is here where they write their own parsing code for filter arguments.

Ha ! Good catch, I didn't dig that deep.

> One option is to add an exclude_tags option (...) to make this smoother I'll add another keyboard shortcut to search (...)

This would indeed be the most simple to implement, and it seems reasonable.

> Do you have any other queries/situations in mind that need extra handling?

I feel like I need to be using the tool to be able to confront it with different situations and be able to answer your question properly; but I'm sure that simply adding such `--exclude-tags` semantics would be enough to cover plenty of them -- if not all.

**Comment by Ninjani** [comment]
Great! On it then 😄

**Comment by ngirard** [comment]
Thanks, and godspeed to you !
